config:
  http_proxy:
test: ok
endpoints:
  - url: https://k8s-worker-node-101:30443/alwayshappy
    headers:
      Host: [ kubenurse.cluster.company.ch ]
    ipVersion: 4 # 4, 6, any
    extraLabels:
      zone: prod
