name: httpstat-metrics

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          version: v1.50.1
